packer {
  required_plugins {
    xenserver= {
     version = "= v0.7.3"
      source = "github.com/ddelnano/xenserver"
   }
  }
}
variable "remote_host" {
  type        = string
  description = "The ip or fqdn of your XCP-ng. It must be the master"
  sensitive   = true
  default     = "10.183.1.131"
}

variable "remote_username" {
  type        = string
  description = "The username used to interact with your XCP-ng"
  sensitive   = true
  default     = "root"
}

variable "remote_password" {
  type        = string
  description = "The password used to interact with your XCP-ng"
  sensitive   = true
  default     = "apqmapqm"
}

variable "sr_iso_name" {
  type        = string
  description = "The ISO-SR to packer will use"
  default     = "ISO"
}

variable "sr_name" {
  type        = string
  description = "The name of the SR to packer will use"
  default     = "Local storage"
}

source "xenserver-iso" "debian12" {
  iso_checksum      = "cb089def0684fd93c9c2fbe45fd16ecc809c949a6fd0c91ee199faefe7d4b82b64658a264a13109d59f1a40ac3080be2f7bd3d8bf3e9cdf509add6d72576a79b"
  iso_url = "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.10.0-amd64-netinst.iso"

  sr_iso_name    = var.sr_iso_name
  sr_name        = var.sr_name
  tools_iso_name = ""

  remote_host     = var.remote_host
  remote_password = var.remote_password
  remote_username = var.remote_username

  http_directory = "http"

  boot_command =  [
        "<wait><wait><wait><esc><wait><wait><wait>",
        "/install.amd/vmlinuz ",
        "initrd=/install.amd/initrd.gz ",
        "auto=true ",
        "domain= ",
        "url=http://10.0.0.143:{{.HTTPPort}}/preseed.cfg ",
        "hostname=debian ",
        "interface=auto ",
        
        // Configuration IP fixe pour l'installation
        "netcfg/disable_autoconfig=true ",
        "netcfg/get_ipaddress=10.0.0.30 ",
        "netcfg/get_netmask=255.255.255.0 ",
        "netcfg/get_gateway=10.0.0.254 ",
        "netcfg/get_nameservers=8.8.8.8 ",
        "netcfg/confirm_static=true ",
        "vga=788 noprompt quiet--- <enter>"
  ]

  # Change this to match the ISO of ubuntu you are using in the iso_url variable
  clone_template = "Generic Linux BIOS"
  vm_name        = "Debian 12 template"
  vm_description = "My first template with packer"
  vcpus_max	 = 4
  vcpus_atstartup = 2
  vm_memory      = 4096 #MB
  network_names = ["REKS-LAN"]
  disk_size      = 20480 #MB
  disk_name      = "debian disk"
  vm_tags        = ["Generated by Packer"]

  ssh_username            = "debian"
  ssh_password            = "debian"
  ssh_wait_timeout        = "60000s"
  ssh_handshake_attempts  = 10000

  output_directory = "packer-debian-12"

  # keep_vm = "on-success"__: Conserve la VM si le build réussit (idéal pour les tests)
  # keep_vm = "on-failure"__: Conserve la VM uniquement si le build échoue (utile pour déboguer)
  # keep_vm = "always"__: Conserve toujours la VM, quel que soit le résultat du build
  keep_vm          = "always"
  format = "xva_compressed"
}

build {
  sources = ["xenserver-iso.debian12"]

  # Transfert des scripts communs
  provisioner "file" {
    source      = "common/"
    destination = "/tmp/common/"
  }

  # Transfert des scripts spécifiques à Debian
  provisioner "file" {
    source      = "debian/"
    destination = "/tmp/debian/"
  }

  # Exécution des scripts
  provisioner "shell" {
    inline = [
      "chmod +x /tmp/common/*.sh /tmp/debian/*.sh",
      
      # Scripts communs
      "sudo /tmp/common/update_system.sh",
      "sudo /tmp/common/harden_ssh.sh",
      "sudo /tmp/common/harden_system.sh",
      "sudo /tmp/common/disable_services.sh",
      
      # Scripts spécifiques à Debian
      "sudo /tmp/debian/install_xen_tools.sh",
      "sudo /tmp/debian/debian_specific.sh",
      
      # Nettoyage final (commun)
      "sudo /tmp/common/cleanup.sh",
      
      # Suppression des scripts
      "rm -rf /tmp/common /tmp/debian"
    ]
  }
}
