packer {
  required_plugins {
    xenserver= {
     version = "= v0.7.3"
      source = "github.com/ddelnano/xenserver"
   }
  }
}

variable "template_logo_url" {
  type        = string
  description = "URL du logo du template pour les métadonnées"
  default     = "images/ubuntu.png"
}

variable "publisher_logo_url" {
  type        = string
  description = "URL du logo du publisher pour les métadonnées"
  default     = "images/cloudtemple.svg"
}

variable "publisher" {
  type        = string
  description = "Nom du owner du template"
  default     = "Cloud Temple"
}

variable "target_platform" {
  type        = string
  description = "Produit cible pour le template. Exemple OpenIaaS ou IaaS VMware"
  default     = "openiaas"
}

variable "remote_host" {
  type        = string
  description = "The ip or fqdn of your XCP-ng. It must be the master"
  sensitive   = true
}

variable "remote_username" {
  type        = string
  description = "The username used to interact with your XCP-ng"
  sensitive   = true
}

variable "remote_password" {
  type        = string
  description = "The password used to interact with your XCP-ng"
  sensitive   = true
}

variable "sr_iso_name" {
  type        = string
  description = "The ISO-SR to packer will use"
  default     = "ISO"
}

variable "sr_name" {
  type        = string
  description = "The name of the SR to packer will use"
  default     = "Local storage"
}

variable "network_names" {
  type        = list(string)
  description = "List of network names to attach to the VM"
}

source "xenserver-iso" "ubuntu22" {
  iso_checksum      = "9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0"
  iso_url           = "https://reks2ee2b1.s3.fr1.cloud-temple.com/packer-vates/ISO/ubuntu-22.04.5-live-server-amd64.iso"

  sr_iso_name    = var.sr_iso_name
  sr_name        = var.sr_name
  tools_iso_name = ""

  remote_host     = var.remote_host
  remote_password = var.remote_password
  remote_username = var.remote_username

  http_directory = "packer/ubuntu/http-ubuntu22"
  boot_wait      = "5s"

  boot_command = ["<spacebar><wait><spacebar><wait><spacebar><wait><spacebar><wait><spacebar><wait>",
    "e<wait>",
    "<down><down><down><end><wait>",
    "<bs><bs><bs>",
    " autoinstall ds=\"nocloud;seedfrom=http://10.0.0.143:{{ .HTTPPort }}/\"",
    "<enter><wait>",
    "<f10>"
    ]

  clone_template = "Generic Linux BIOS"
  vm_name        = "template-ubuntu-22.04"
  vm_description = "Ubuntu 22.04 LTS (Jammy Jellyfish). \nDefault login : 'admct'. \nDefault password: 'InitCT@2025'"
  vcpus_max      = 4
  vcpus_atstartup = 2
  vm_memory      = 4096 #MB
  network_names  = var.network_names
  disk_size      = 20480 #MB
  disk_name      = "ubuntu-22.04-disk-0"
  vm_tags        = ["Generated by Packer", "Ubuntu", "cloud-init"]

  ssh_username            = "admct"
  ssh_password            = "InitCT@2025"

  ssh_wait_timeout        = "60000s"
  ssh_handshake_attempts  = 10000

  communicator = "ssh"
  output_directory = "packer-template-ubuntu-22.04"
  pause_before_connecting = "60s"

  # Conserver la VM en cas d'échec pour faciliter le débogage
  keep_vm          = "never"
  format = "xva_compressed"
}

build {
  sources = ["xenserver-iso.ubuntu22"]

  provisioner "file" {
    source      = "packer/common/"
    destination = "/tmp/"
  }

  provisioner "file" {
    source      = "packer/ubuntu/extras/"
    destination = "/tmp/"
  }

  # Exécution des scripts
  provisioner "shell" {
    inline = [
      "chmod +x /tmp/*.sh",

      # Scripts communs
      "sudo /tmp/update_system.sh",
      "sudo /tmp/harden_ssh.sh",
      "sudo /tmp/harden_system.sh",
      "sudo /tmp/setup_motd.sh",
      
      # Scripts spécifiques à Ubuntu
      "sudo /tmp/ubuntu_specific.sh",

      # Suppression des scripts
      "rm -f /tmp/*.sh"
    ]
  }
}
